2024-03-11 15:34:29,815 - __main__ - INFO - Bot Process stopped, which was running before 18s
2024-03-11 15:34:29,816 - __main__ - INFO - Bot Process stopped, which was running before 18s
2024-03-11 15:34:36,945 - __main__ - INFO - Bot started successfuly.
2024-03-11 15:34:36,949 - __main__ - INFO - Bot started successfuly.
2024-03-11 15:50:12,090 - __main__ - INFO - Bot Process stopped, which was running before 15min 32s
2024-03-11 15:50:17,775 - __main__ - INFO - Bot started successfuly.
2024-03-11 15:50:17,780 - __main__ - INFO - Bot started successfuly.
2024-03-11 16:03:23,106 - __main__ - INFO - Bot Process stopped, which was running before 13min 4s
2024-03-11 16:03:23,107 - __main__ - INFO - Bot Process stopped, which was running before 13min 4s
2024-03-11 16:03:28,073 - __main__ - INFO - Bot started successfuly.
2024-03-11 16:03:28,077 - __main__ - INFO - Bot started successfuly.
2024-03-11 16:03:53,294 - __main__ - INFO - Bot Process stopped, which was running before 24s
2024-03-11 16:03:53,306 - __main__ - INFO - Bot Process stopped, which was running before 24s
2024-03-11 16:05:15,047 - __main__ - INFO - Bot started successfuly.
2024-03-11 16:05:15,061 - __main__ - INFO - Bot started successfuly.
2024-03-11 16:06:15,911 - __main__ - INFO - Bot Process stopped, which was running before 1min 0s
2024-03-11 16:06:15,913 - __main__ - INFO - Bot Process stopped, which was running before 1min 0s
2024-03-11 16:06:22,831 - __main__ - INFO - Bot started successfuly.
2024-03-11 16:06:22,853 - __main__ - INFO - Bot started successfuly.
2024-03-11 16:07:29,690 - __main__ - INFO - Bot started successfuly.
2024-03-11 16:07:29,697 - __main__ - INFO - Bot started successfuly.
2024-03-11 16:11:33,606 - __main__ - INFO - Bot Process stopped, which was running before 4min 3s
2024-03-11 16:11:33,607 - __main__ - INFO - Bot Process stopped, which was running before 4min 3s
2024-03-11 16:11:41,430 - __main__ - INFO - Bot started successfuly.
2024-03-11 16:11:41,440 - __main__ - INFO - Bot started successfuly.
2024-03-11 16:13:27,663 - __main__ - INFO - Bot Process stopped, which was running before 1min 45s
2024-03-11 16:13:27,667 - __main__ - INFO - Bot Process stopped, which was running before 1min 45s
2024-03-11 16:13:33,880 - __main__ - INFO - Bot started successfuly.
2024-03-11 16:13:33,890 - __main__ - INFO - Bot started successfuly.
2024-03-11 16:14:33,657 - __main__ - INFO - Bot Process stopped, which was running before 58s
2024-03-11 16:14:33,658 - __main__ - INFO - Bot Process stopped, which was running before 58s
2024-03-11 16:14:42,680 - __main__ - INFO - Bot started successfuly.
2024-03-11 16:14:42,689 - __main__ - INFO - Bot started successfuly.
2024-03-11 16:15:15,032 - __main__ - INFO - Bot Process stopped, which was running before 31s
2024-03-11 16:15:15,034 - __main__ - INFO - Bot Process stopped, which was running before 31s
2024-03-11 16:15:20,215 - __main__ - INFO - Bot started successfuly.
2024-03-11 16:15:20,221 - __main__ - INFO - Bot started successfuly.
2024-03-11 16:29:00,896 - __main__ - INFO - Bot started successfuly.
2024-03-11 16:29:00,924 - __main__ - INFO - Bot started successfuly.
2024-03-11 16:58:40,239 - __main__ - INFO - Bot Process stopped, which was running before 29min 39s
2024-03-11 16:58:40,240 - __main__ - INFO - Bot Process stopped, which was running before 29min 39s
2024-03-11 16:58:52,385 - __main__ - INFO - Bot started successfuly.
2024-03-11 16:58:52,415 - __main__ - INFO - Bot started successfuly.
2024-03-11 16:59:27,094 - __main__ - INFO - Bot Process stopped, which was running before 33s
2024-03-11 16:59:27,096 - __main__ - INFO - Bot Process stopped, which was running before 33s
2024-03-11 16:59:34,843 - __main__ - INFO - Bot started successfuly.
2024-03-11 16:59:34,847 - __main__ - INFO - Bot started successfuly.
2024-03-11 17:00:28,850 - __main__ - INFO - Bot Process stopped, which was running before 52s
2024-03-11 17:00:28,853 - __main__ - INFO - Bot Process stopped, which was running before 53s
2024-03-11 17:00:51,971 - __main__ - INFO - Bot started successfuly.
2024-03-11 17:00:51,980 - __main__ - INFO - Bot started successfuly.
2024-03-11 17:01:55,753 - __main__ - INFO - Bot Process stopped, which was running before 1min 2s
2024-03-11 17:01:55,754 - __main__ - INFO - Bot Process stopped, which was running before 1min 3s
2024-03-11 17:02:13,230 - __main__ - INFO - Bot started successfuly.
2024-03-11 17:02:13,237 - __main__ - INFO - Bot started successfuly.
2024-03-11 17:02:57,828 - __main__ - INFO - Bot Process stopped, which was running before 44s
2024-03-11 17:02:57,829 - __main__ - INFO - Bot Process stopped, which was running before 44s
2024-03-11 17:03:42,492 - __main__ - INFO - Bot started successfuly.
2024-03-11 17:03:42,499 - __main__ - INFO - Bot started successfuly.
2024-03-11 17:10:21,856 - __main__ - INFO - Bot Process stopped, which was running before 6min 38s
2024-03-11 17:10:21,860 - __main__ - INFO - Bot Process stopped, which was running before 6min 37s
2024-03-11 17:10:42,493 - __main__ - INFO - Bot started successfuly.
2024-03-11 17:10:42,553 - __main__ - INFO - Bot started successfuly.
2024-03-11 17:13:52,550 - __main__ - INFO - Bot Process stopped, which was running before 3min 9s
2024-03-11 17:13:52,553 - __main__ - INFO - Bot Process stopped, which was running before 3min 9s
2024-03-11 17:13:59,427 - __main__ - INFO - Bot started successfuly.
2024-03-11 17:13:59,434 - __main__ - INFO - Bot started successfuly.
2024-03-11 17:14:38,135 - __main__ - INFO - Bot Process stopped, which was running before 37s
2024-03-11 17:14:38,178 - __main__ - INFO - Bot Process stopped, which was running before 37s
2024-03-11 17:14:44,611 - __main__ - INFO - Bot started successfuly.
2024-03-11 17:14:44,616 - __main__ - INFO - Bot started successfuly.
2024-03-16 09:36:25,421 - __main__ - INFO - Bot started successfuly.
2024-03-16 09:36:25,480 - __main__ - INFO - Bot started successfuly.
2024-03-16 09:40:21,846 - __main__ - INFO - Bot Process stopped, which was running before 3min 55s
2024-03-16 09:40:21,848 - __main__ - INFO - Bot Process stopped, which was running before 3min 55s
2024-03-16 09:42:38,195 - __main__ - INFO - Bot started successfuly.
2024-03-16 09:42:38,228 - __main__ - INFO - Bot started successfuly.
2024-03-16 09:57:43,637 - __main__ - INFO - Bot Process stopped, which was running before 15min 4s
2024-03-16 09:57:43,648 - __main__ - INFO - Bot Process stopped, which was running before 15min 4s
2024-03-23 14:10:37,563 - __main__ - INFO - Bot started successfuly.
2024-03-23 14:10:37,572 - __main__ - INFO - Bot started successfuly.
2024-03-24 10:46:12,116 - __main__ - INFO - Bot started successfuly.
2024-03-24 10:46:12,130 - __main__ - INFO - Bot started successfuly.
2024-03-24 10:49:22,097 - __main__ - INFO - Bot started successfuly.
2024-03-24 10:49:22,113 - __main__ - INFO - Bot started successfuly.
2024-03-24 10:49:22,139 - __main__ - INFO - Error in DBolt: [WinError 2] Le fichier spécifié est introuvable
2024-03-24 10:49:22,143 - __main__ - INFO - Bot Process stopped, which was running before 0s
2024-03-24 10:49:22,152 - __main__ - INFO - Error in RACUBot: [WinError 2] Le fichier spécifié est introuvable
2024-03-24 10:49:22,162 - __main__ - INFO - Bot Process stopped, which was running before 2min 42s
2024-03-24 10:51:36,480 - __main__ - INFO - Bot started successfuly.
2024-03-24 10:51:36,480 - __main__ - INFO - Bot started successfuly.
2024-03-24 11:44:49,243 - __main__ - INFO - Bot started successfuly.
2024-03-24 11:44:49,250 - __main__ - INFO - Bot started successfuly.
2024-03-24 11:45:45,626 - __main__ - INFO - Bot started successfuly.
2024-03-24 11:45:45,636 - __main__ - INFO - Bot started successfuly.
2024-03-24 11:46:31,195 - __main__ - INFO - Bot started successfuly.
2024-03-24 11:46:31,207 - __main__ - INFO - Bot started successfuly.
2024-03-24 11:47:19,188 - __main__ - INFO - Bot started successfuly.
2024-03-24 11:47:19,203 - __main__ - INFO - Bot started successfuly.
2024-03-24 11:48:26,853 - __main__ - INFO - Bot started successfuly.
2024-03-24 11:48:26,853 - __main__ - INFO - Bot started successfuly.
2024-03-24 11:57:06,064 - __main__ - INFO - Bot started successfuly.
2024-03-24 11:57:06,064 - __main__ - INFO - Bot started successfuly.
2024-03-24 11:57:53,447 - __main__ - INFO - Bot started successfuly.
2024-03-24 12:03:26,353 - __main__ - INFO - Bot started successfuly.
2024-03-24 12:03:26,369 - __main__ - INFO - Bot started successfuly.
2024-03-24 12:07:40,104 - __main__ - INFO - Bot started successfuly.
2024-03-24 12:07:40,104 - __main__ - INFO - Bot started successfuly.
2024-03-24 12:08:46,926 - __main__ - INFO - Bot started successfuly.
2024-03-24 12:08:46,931 - __main__ - INFO - Bot started successfuly.
2024-03-24 12:09:46,264 - __main__ - INFO - Bot started successfuly.
2024-03-24 12:09:46,279 - __main__ - INFO - Bot started successfuly.
2024-03-24 12:10:44,638 - __main__ - INFO - Bot started successfuly.
2024-03-24 12:10:44,649 - __main__ - INFO - Bot started successfuly.
2024-03-24 12:11:17,002 - __main__ - INFO - Bot started successfuly.
2024-03-24 12:11:17,002 - __main__ - INFO - Bot started successfuly.
2024-03-24 12:11:58,925 - __main__ - INFO - Bot started successfuly.
2024-03-24 12:11:58,929 - __main__ - INFO - Bot started successfuly.
2024-03-24 12:14:53,389 - __main__ - INFO - Bot started successfuly.
2024-03-24 12:14:53,393 - __main__ - INFO - Bot started successfuly.
2024-03-24 12:24:51,264 - __main__ - INFO - Bot started successfuly.
2024-03-24 12:24:51,269 - __main__ - INFO - Bot started successfuly.
2024-03-24 12:25:43,859 - __main__ - INFO - Bot started successfuly.
2024-03-24 12:25:43,875 - __main__ - INFO - Bot started successfuly.
2024-03-24 12:27:11,382 - __main__ - INFO - Bot started successfuly.
2024-03-24 12:27:11,385 - __main__ - INFO - Bot started successfuly.
2024-03-24 12:30:36,687 - __main__ - INFO - Bot started successfuly.
2024-03-24 12:30:36,687 - __main__ - INFO - Bot started successfuly.
2024-03-24 12:34:21,250 - __main__ - INFO - Bot started successfuly.
2024-03-24 12:34:21,266 - __main__ - INFO - Bot started successfuly.
2024-03-24 12:35:05,049 - __main__ - INFO - Bot started successfuly.
2024-03-24 12:35:05,054 - __main__ - INFO - Bot started successfuly.
2024-03-24 12:35:36,278 - __main__ - INFO - Bot started successfuly.
2024-03-24 12:35:36,282 - __main__ - INFO - Bot started successfuly.
2024-03-24 12:38:15,688 - __main__ - INFO - Bot started successfuly.
2024-03-24 12:38:15,703 - __main__ - INFO - Bot started successfuly.
2024-03-24 12:39:16,172 - __main__ - INFO - Bot started successfuly.
2024-03-24 12:39:16,188 - __main__ - INFO - Bot started successfuly.
2024-03-24 12:40:28,253 - __main__ - INFO - Bot started successfuly.
2024-03-24 12:40:28,269 - __main__ - INFO - Bot started successfuly.
2024-03-24 12:44:37,446 - __main__ - INFO - Bot started successfuly.
2024-03-24 12:44:37,451 - __main__ - INFO - Bot started successfuly.
2024-05-11 15:06:31,489 - __main__ - INFO - Bot started successfuly.
2024-05-11 15:06:31,673 - __main__ - INFO - Bot started successfuly.
2024-05-11 15:09:35,778 - __main__ - INFO - Bot started successfuly.
2024-05-11 15:09:35,783 - __main__ - INFO - Bot started successfuly.
2024-05-11 15:10:20,102 - __main__ - INFO - Bot started successfuly.
2024-05-11 15:10:20,110 - __main__ - INFO - Bot started successfuly.
2024-05-11 16:29:58,924 - __main__ - INFO - Bot started successfuly.
2024-05-11 16:29:58,963 - __main__ - INFO - Bot started successfuly.
2024-05-11 17:44:53,296 - __main__ - INFO - Bot started successfuly.
2024-05-11 17:44:53,302 - __main__ - INFO - Bot started successfuly.
2024-05-11 17:45:35,174 - __main__ - INFO - Bot started successfuly.
2024-05-11 17:45:35,179 - __main__ - INFO - Bot started successfuly.
2024-05-11 17:47:11,708 - __main__ - INFO - Bot started successfuly.
2024-05-11 17:47:11,712 - __main__ - INFO - Bot started successfuly.
2024-05-11 17:47:57,082 - __main__ - INFO - Bot started successfuly.
2024-05-11 17:47:57,086 - __main__ - INFO - Bot started successfuly.
2024-05-11 17:48:40,287 - __main__ - INFO - Bot started successfuly.
2024-05-11 17:48:40,292 - __main__ - INFO - Bot started successfuly.
2024-05-11 17:49:14,302 - __main__ - INFO - Bot started successfuly.
2024-05-11 17:49:14,992 - __main__ - INFO - Bot started successfuly.
2024-05-11 17:49:35,209 - __main__ - INFO - Bot started successfuly.
2024-05-11 17:49:35,221 - __main__ - INFO - Bot started successfuly.
2024-05-11 17:52:41,780 - __main__ - INFO - Bot started successfuly.
2024-05-11 17:52:41,785 - __main__ - INFO - Bot started successfuly.
2024-05-11 17:56:09,010 - __main__ - INFO - Bot started successfuly.
2024-05-11 17:56:09,018 - __main__ - INFO - Bot started successfuly.
2024-05-11 17:59:05,129 - __main__ - INFO - Bot started successfuly.
2024-05-11 17:59:05,133 - __main__ - INFO - Bot started successfuly.
2024-05-12 09:17:14,998 - __main__ - INFO - Bot started successfuly.
2024-05-12 09:17:15,263 - __main__ - INFO - Bot started successfuly.
2024-05-12 09:36:02,793 - __main__ - INFO - Bot started successfuly.
2024-05-12 09:36:02,804 - __main__ - INFO - Bot started successfuly.
2024-05-12 09:41:55,691 - __main__ - INFO - Bot started successfuly.
2024-05-12 09:41:55,697 - __main__ - INFO - Bot started successfuly.
2024-05-12 09:46:22,197 - __main__ - INFO - Bot started successfuly.
2024-05-12 09:46:22,204 - __main__ - INFO - Bot started successfuly.
2024-05-12 10:21:40,268 - __main__ - INFO - Bot started successfuly.
2024-05-12 10:21:40,276 - __main__ - INFO - Bot started successfuly.
2024-05-12 10:25:48,924 - __main__ - INFO - Bot started successfuly.
2024-05-12 10:25:48,929 - __main__ - INFO - Bot started successfuly.
2024-05-12 11:42:03,521 - __main__ - INFO - Bot started successfuly.
2024-05-12 11:42:03,527 - __main__ - INFO - Bot started successfuly.
2024-05-12 12:49:22,839 - __main__ - INFO - Bot started successfuly.
2024-05-12 12:49:22,844 - __main__ - INFO - Bot started successfuly.
2024-05-12 13:00:25,900 - __main__ - INFO - Bot started successfuly.
2024-05-12 13:00:25,934 - __main__ - INFO - Bot started successfuly.
2024-05-12 17:40:16,619 - __main__ - INFO - Bot started successfuly.
2024-05-12 17:40:16,626 - __main__ - INFO - Bot started successfuly.
2024-05-12 17:40:40,227 - __main__ - INFO - Bot started successfuly.
2024-05-12 17:40:40,231 - __main__ - INFO - Bot started successfuly.
2024-05-12 17:41:21,342 - __main__ - INFO - Bot started successfuly.
2024-05-12 17:41:21,347 - __main__ - INFO - Bot started successfuly.
2024-05-12 17:41:56,773 - __main__ - INFO - Bot started successfuly.
2024-05-12 17:41:56,773 - __main__ - INFO - Bot started successfuly.
2024-05-12 17:42:55,898 - __main__ - INFO - Bot started successfuly.
2024-05-12 17:42:55,906 - __main__ - INFO - Bot started successfuly.
2024-05-12 20:22:46,572 - __main__ - INFO - Bot started successfuly.
2024-05-12 20:22:46,578 - __main__ - INFO - Bot started successfuly.
2024-05-17 10:14:46,560 - __main__ - INFO - Bot started successfuly.
2024-05-17 10:14:46,580 - __main__ - INFO - Bot started successfuly.
2024-05-17 10:16:46,941 - __main__ - INFO - Bot started successfuly.
2024-05-17 10:16:46,946 - __main__ - INFO - Bot started successfuly.
2024-05-17 10:48:53,805 - __main__ - INFO - Bot started successfuly.
2024-05-17 10:48:53,813 - __main__ - INFO - Bot started successfuly.
2024-07-13 11:31:07,660 - __main__ - INFO - Bot started successfuly.
2024-07-13 11:31:07,662 - __main__ - INFO - Bot started successfuly.
2024-07-13 11:32:31,952 - __main__ - INFO - Bot started successfuly.
2024-07-13 11:32:31,954 - __main__ - INFO - Bot started successfuly.
2024-07-13 11:40:27,767 - __main__ - INFO - Bot started successfuly.
2024-07-13 11:40:27,769 - __main__ - INFO - Bot started successfuly.
2024-07-13 11:46:08,924 - __main__ - INFO - Bot started successfuly.
2024-07-13 11:46:08,926 - __main__ - INFO - Bot started successfuly.
2024-07-13 11:46:24,703 - __main__ - INFO - Bot started successfuly.
2024-07-13 11:46:24,706 - __main__ - INFO - Bot started successfuly.
2024-07-13 11:47:15,850 - __main__ - INFO - Bot started successfuly.
2024-07-13 11:47:15,853 - __main__ - INFO - Bot started successfuly.
2024-07-13 11:50:04,973 - __main__ - INFO - Bot started successfuly.
2024-07-13 11:50:04,978 - __main__ - INFO - Bot started successfuly.
2024-07-13 11:57:39,741 - __main__ - INFO - Bot started successfuly.
2024-07-13 11:57:39,744 - __main__ - INFO - Bot started successfuly.
2024-07-13 11:58:48,611 - __main__ - INFO - Bot started successfuly.
2024-07-13 11:58:48,614 - __main__ - INFO - Bot started successfuly.
2024-07-13 11:59:32,802 - __main__ - INFO - Bot started successfuly.
2024-07-13 11:59:32,805 - __main__ - INFO - Bot started successfuly.
2024-07-13 11:59:59,655 - __main__ - INFO - Bot started successfuly.
2024-07-13 11:59:59,661 - __main__ - INFO - Bot started successfuly.
2024-07-13 12:10:35,705 - __main__ - INFO - Bot started successfuly.
2024-07-13 12:10:35,707 - __main__ - INFO - Bot started successfuly.
2024-07-13 12:13:01,739 - __main__ - INFO - Bot started successfuly.
2024-07-13 12:13:01,741 - __main__ - INFO - Bot started successfuly.
2024-07-13 12:13:21,392 - __main__ - INFO - Bot started successfuly.
2024-07-13 12:13:21,397 - __main__ - INFO - Bot started successfuly.
2024-08-18 20:27:48,702 - __main__ - INFO - Bot started successfuly.
2024-08-18 20:27:48,705 - __main__ - INFO - Bot started successfuly.
2024-08-19 12:34:18,443 - __main__ - INFO - Bot started successfully.
2024-08-19 12:34:18,443 - __main__ - INFO - Error in DBolt: module 'docker.errors' has no attribute 'ContainerError'
2024-08-19 12:34:18,444 - __main__ - INFO - Bot Process stopped, which was running before 0s
2024-08-19 12:34:18,445 - __main__ - INFO - Bot started successfully.
2024-08-19 12:34:18,445 - __main__ - INFO - Error in RACUBot: module 'docker.errors' has no attribute 'ContainerError'
2024-08-19 12:34:18,446 - __main__ - INFO - Bot Process stopped, which was running before 0s
2024-08-19 12:34:41,468 - __main__ - INFO - Bot started successfully.
2024-08-19 12:34:41,469 - __main__ - INFO - Error in DBolt: module 'docker.errors' has no attribute 'ContainerError'
2024-08-19 12:34:41,470 - __main__ - INFO - Bot Process stopped, which was running before 0s
2024-08-19 12:34:41,470 - __main__ - INFO - Bot started successfully.
2024-08-19 12:34:41,470 - __main__ - INFO - Error in RACUBot: module 'docker.errors' has no attribute 'ContainerError'
2024-08-19 12:34:41,471 - __main__ - INFO - Bot Process stopped, which was running before 0s
2024-08-19 12:36:13,875 - __main__ - INFO - Bot started successfully.
2024-08-19 12:36:13,876 - __main__ - INFO - Error in DBolt: module 'docker.errors' has no attribute 'ContainerError'
2024-08-19 12:36:13,878 - __main__ - INFO - Bot Process stopped, which was running before 0s
2024-08-19 12:36:13,879 - __main__ - INFO - Bot started successfully.
2024-08-19 12:36:13,880 - __main__ - INFO - Error in RACUBot: module 'docker.errors' has no attribute 'ContainerError'
2024-08-19 12:36:13,883 - __main__ - INFO - Bot Process stopped, which was running before 0s
2024-08-19 12:38:02,301 - __main__ - INFO - Bot started successfully.
2024-08-19 12:38:02,302 - __main__ - INFO - Error in DBolt: 'function' object has no attribute 'run'
2024-08-19 12:38:02,304 - __main__ - INFO - Bot started successfully.
2024-08-19 12:38:02,305 - __main__ - INFO - Error in RACUBot: 'function' object has no attribute 'run'
2024-08-19 12:55:50,513 - __main__ - INFO - Bot started successfully.
2024-08-19 12:55:50,518 - __main__ - INFO - Bot started successfully.
2024-08-19 12:58:16,232 - __main__ - INFO - Bot started successfully.
2024-08-19 12:58:16,235 - __main__ - INFO - Bot started successfully.
2024-08-19 13:00:27,330 - __main__ - INFO - Bot started successfully.
2024-08-19 13:00:27,333 - __main__ - INFO - Bot started successfully.
2024-08-19 13:21:13,918 - __main__ - INFO - Bot started successfully.
2024-08-19 13:21:13,922 - __main__ - INFO - Bot started successfully.
2024-08-19 13:21:16,223 - __main__ - INFO - Error in RACUBot: 400 Client Error for http+docker://localnpipe/v1.46/containers/cda9f186fd35ecfb8677224d1e34a16fbd71e551a87a4c1bfffb6905407866ef/start: Bad Request ("failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "py": executable file not found in $PATH: unknown")
2024-08-19 13:21:16,225 - __main__ - INFO - Bot Process stopped, which was running before 0s
2024-08-19 13:21:16,365 - __main__ - INFO - Error in DBolt: 400 Client Error for http+docker://localnpipe/v1.46/containers/1edf73d2f7cb5534ba3dba208e5602cde6393c1b09f000170eb0bca0b60010f7/start: Bad Request ("failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "py": executable file not found in $PATH: unknown")
2024-08-19 13:21:16,365 - __main__ - INFO - Bot Process stopped, which was running before 0s
2024-08-19 13:27:56,427 - __main__ - INFO - Bot started successfully.
2024-08-19 13:27:56,430 - __main__ - INFO - Bot started successfully.
2024-08-19 13:31:09,523 - __main__ - INFO - Bot started successfully.
2024-08-19 13:31:09,525 - __main__ - INFO - Bot started successfully.
2024-08-19 13:31:10,360 - __main__ - INFO - python: can't open file '/app/DBolt/main.py': [Errno 2] No such file or directory
2024-08-19 13:31:10,440 - __main__ - INFO - python: can't open file '/app/RACUBot/main.py': [Errno 2] No such file or directory
2024-08-19 13:32:22,385 - __main__ - INFO - Bot started successfully.
2024-08-19 13:32:22,389 - __main__ - INFO - Bot started successfully.
2024-08-19 13:32:23,009 - __main__ - INFO - python: can't open file '//main.py': [Errno 2] No such file or directory
2024-08-19 13:32:23,023 - __main__ - INFO - python: can't open file '//main.py': [Errno 2] No such file or directory
2024-08-19 13:33:38,451 - __main__ - INFO - Bot started successfully.
2024-08-19 13:33:38,454 - __main__ - INFO - Bot started successfully.
2024-08-19 13:33:39,191 - __main__ - INFO - python: can't open file '/app/RACUBot/main.py': [Errno 2] No such file or directory
2024-08-19 13:33:39,370 - __main__ - INFO - python: can't open file '/app/DBolt/main.py': [Errno 2] No such file or directory
2024-08-19 13:34:01,877 - __main__ - INFO - Bot started successfully.
2024-08-19 13:34:01,880 - __main__ - INFO - Bot started successfully.
2024-08-19 13:34:02,545 - __main__ - INFO - Traceback (most recent call last):
2024-08-19 13:34:02,545 - __main__ - INFO - File "/app/RACUBot/main.py", line 1, in <module>
2024-08-19 13:34:02,546 - __main__ - INFO - Traceback (most recent call last):
2024-08-19 13:34:02,547 - __main__ - INFO - File "/app/DBolt/main.py", line 1, in <module>
2024-08-19 13:34:02,549 - __main__ - INFO - from json_m.json_m import json_file, Operation
2024-08-19 13:34:02,550 - __main__ - INFO - from json_m.json_m import json_file, Operation
2024-08-19 13:34:02,550 - __main__ - INFO - ModuleNotFoundError: No module named 'json_m'
2024-08-19 13:34:02,551 - __main__ - INFO - ModuleNotFoundError: No module named 'json_m'
2024-08-19 13:36:04,284 - __main__ - INFO - Bot started successfully.
2024-08-19 13:36:04,792 - __main__ - INFO - Traceback (most recent call last):
2024-08-19 13:36:04,792 - __main__ - INFO - File "/app/DBolt/main.py", line 2, in <module>
2024-08-19 13:36:04,795 - __main__ - INFO - with open("config.json", "r") as f:
2024-08-19 13:36:04,796 - __main__ - INFO - ^^^^^^^^^^^^^^^^^^^^^^^^
2024-08-19 13:36:04,796 - __main__ - INFO - FileNotFoundError: [Errno 2] No such file or directory: 'config.json'
2024-08-19 13:36:49,210 - __main__ - INFO - Bot started successfully.
2024-08-19 13:36:50,707 - __main__ - INFO - Traceback (most recent call last):
2024-08-19 13:36:50,707 - __main__ - INFO - File "/app/DBolt/main.py", line 4, in <module>
2024-08-19 13:36:50,712 - __main__ - INFO - with open(os.path.join(os.getcwd(), "config.json"), "r") as f:
2024-08-19 13:36:50,712 - __main__ - INFO - ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-08-19 13:36:50,713 - __main__ - INFO - FileNotFoundError: [Errno 2] No such file or directory: '/config.json'
2024-08-19 13:37:10,828 - __main__ - INFO - Bot started successfully.
2024-08-19 13:37:11,318 - __main__ - INFO - /
2024-08-19 13:37:11,318 - __main__ - INFO - Traceback (most recent call last):
2024-08-19 13:37:11,318 - __main__ - INFO - File "/app/DBolt/main.py", line 6, in <module>
2024-08-19 13:37:11,321 - __main__ - INFO - with open(os.path.join(os.getcwd(), "config.json"), "r") as f:
2024-08-19 13:37:11,321 - __main__ - INFO - ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-08-19 13:37:11,322 - __main__ - INFO - FileNotFoundError: [Errno 2] No such file or directory: '/config.json'
2024-08-19 13:37:52,455 - __main__ - INFO - Bot started successfully.
2024-08-19 13:37:52,925 - __main__ - INFO - /
2024-08-19 13:37:52,926 - __main__ - INFO - Traceback (most recent call last):
2024-08-19 13:37:52,926 - __main__ - INFO - File "/app/DBolt/main.py", line 11, in <module>
2024-08-19 13:37:52,928 - __main__ - INFO - import discord
2024-08-19 13:37:52,928 - __main__ - INFO - ModuleNotFoundError: No module named 'discord'
2024-08-19 13:43:16,554 - __main__ - INFO - Bot started successfully.
2024-08-19 13:43:16,965 - __main__ - INFO - Error in DBolt: expected str, bytes or os.PathLike object, not builtin_function_or_method
2024-08-19 13:43:16,965 - __main__ - INFO - Bot Process stopped, which was running before 0s
2024-08-19 13:43:57,864 - __main__ - INFO - Bot started successfully.
2024-08-19 13:43:58,216 - __main__ - INFO - Error in DBolt: expected str, bytes or os.PathLike object, not builtin_function_or_method
2024-08-19 13:43:58,217 - __main__ - INFO - Bot Process stopped, which was running before 0s
2024-08-19 13:44:25,329 - __main__ - INFO - Bot started successfully.
2024-08-19 13:44:25,715 - __main__ - INFO - Error in DBolt: expected str, bytes or os.PathLike object, not builtin_function_or_method
2024-08-19 13:44:25,716 - __main__ - INFO - Bot Process stopped, which was running before 0s
2024-08-19 13:44:46,497 - __main__ - INFO - Bot started successfully.
2024-08-19 13:44:46,912 - __main__ - INFO - Error in DBolt: expected str, bytes or os.PathLike object, not builtin_function_or_method
2024-08-19 13:44:46,913 - __main__ - INFO - Bot Process stopped, which was running before 0s
2024-08-19 13:44:56,058 - __main__ - INFO - Bot started successfully.
2024-08-19 13:44:56,466 - __main__ - INFO - Error in DBolt: expected str, bytes or os.PathLike object, not builtin_function_or_method
2024-08-19 13:44:56,466 - __main__ - INFO - Bot Process stopped, which was running before 0s
2024-08-19 13:45:50,665 - __main__ - INFO - Bot started successfully.
2024-08-19 13:45:51,059 - __main__ - INFO - Error in DBolt: expected str, bytes or os.PathLike object, not builtin_function_or_method
2024-08-19 13:45:51,059 - __main__ - INFO - Bot Process stopped, which was running before 0s
2024-08-19 13:46:14,450 - __main__ - INFO - Bot started successfully.
2024-08-19 13:46:14,852 - __main__ - INFO - Bot Process stopped, which was running before 0s
2024-08-19 13:46:40,589 - __main__ - INFO - Bot started successfully.
2024-08-19 13:46:41,016 - __main__ - INFO - Installing module discord.py...
2024-08-19 13:46:41,141 - __main__ - INFO - Install output for discord.py: 
2024-08-19 13:46:41,141 - __main__ - INFO - Error installing discord.py: 
2024-08-19 13:46:41,545 - __main__ - INFO - Traceback (most recent call last):
2024-08-19 13:46:41,545 - __main__ - INFO - File "/app/DBolt/main.py", line 8, in <module>
2024-08-19 13:46:41,545 - __main__ - INFO - import discord
2024-08-19 13:46:41,545 - __main__ - INFO - ModuleNotFoundError: No module named 'discord'
2024-08-19 13:48:59,410 - __main__ - INFO - Bot started successfully.
2024-08-19 13:48:59,784 - __main__ - INFO - Installing module discord.py...
2024-08-19 13:48:59,914 - __main__ - INFO - Install output for discord.py: 
2024-08-19 13:48:59,915 - __main__ - INFO - Error installing discord.py: 
2024-08-19 13:49:00,234 - __main__ - INFO - Traceback (most recent call last):
2024-08-19 13:49:00,235 - __main__ - INFO - File "/app/DBolt/main.py", line 8, in <module>
2024-08-19 13:49:00,235 - __main__ - INFO - import discord
2024-08-19 13:49:00,235 - __main__ - INFO - ModuleNotFoundError: No module named 'discord'
2024-08-19 13:50:23,403 - __main__ - INFO - Bot started successfully.
2024-08-19 13:50:23,827 - __main__ - INFO - Installing module discord.py...
2024-08-19 13:50:23,966 - __main__ - INFO - Install output for discord.py: 
2024-08-19 13:50:23,967 - __main__ - INFO - Error installing discord.py: 
2024-08-19 13:50:24,332 - __main__ - INFO - Traceback (most recent call last):
2024-08-19 13:50:24,333 - __main__ - INFO - File "/app/DBolt/main.py", line 8, in <module>
2024-08-19 13:50:24,333 - __main__ - INFO - import discord
2024-08-19 13:50:24,333 - __main__ - INFO - ModuleNotFoundError: No module named 'discord'
2024-08-19 13:55:36,926 - __main__ - INFO - Bot started successfully.
2024-08-19 13:55:37,290 - __main__ - INFO - Installing module discord.py...
2024-08-19 13:55:37,413 - __main__ - INFO - Install output for discord.py: 
2024-08-19 13:55:37,413 - __main__ - INFO - Error installing discord.py: 
2024-08-19 13:55:37,853 - __main__ - INFO - Traceback (most recent call last):
2024-08-19 13:55:37,853 - __main__ - INFO - File "/app/DBolt/main.py", line 8, in <module>
2024-08-19 13:55:37,854 - __main__ - INFO - import discord
2024-08-19 13:55:37,854 - __main__ - INFO - ModuleNotFoundError: No module named 'discord'
2024-08-19 13:56:20,820 - __main__ - INFO - Bot started successfully.
2024-08-19 13:56:21,225 - __main__ - INFO - Installing module discord.py...
2024-08-19 13:56:21,363 - __main__ - INFO - Install output for discord.py: 
2024-08-19 13:56:21,364 - __main__ - INFO - Error installing discord.py: 
2024-08-19 13:56:21,726 - __main__ - INFO - Traceback (most recent call last):
2024-08-19 13:56:21,726 - __main__ - INFO - File "/app/DBolt/main.py", line 8, in <module>
2024-08-19 13:56:21,727 - __main__ - INFO - import discord
2024-08-19 13:56:21,727 - __main__ - INFO - ModuleNotFoundError: No module named 'discord'
2024-08-19 13:56:34,177 - __main__ - INFO - Bot started successfully.
2024-08-19 13:56:34,560 - __main__ - INFO - Installing module discord.py...
2024-08-19 13:56:34,680 - __main__ - INFO - Install output for discord.py: 
2024-08-19 13:56:34,681 - __main__ - INFO - Error installing discord.py: 
2024-08-19 13:56:35,098 - __main__ - INFO - Traceback (most recent call last):
2024-08-19 13:56:35,099 - __main__ - INFO - File "/app/DBolt/main.py", line 8, in <module>
2024-08-19 13:56:35,099 - __main__ - INFO - import discord
2024-08-19 13:56:35,100 - __main__ - INFO - ModuleNotFoundError: No module named 'discord'
2024-08-19 13:56:48,547 - __main__ - INFO - Bot started successfully.
2024-08-19 13:56:48,957 - __main__ - INFO - Installing module discord.py...
2024-08-19 13:56:49,087 - __main__ - INFO - Install output for discord.py: 
2024-08-19 13:56:49,088 - __main__ - INFO - Error installing discord.py: 
2024-08-19 13:56:49,386 - __main__ - INFO - Traceback (most recent call last):
2024-08-19 13:56:49,386 - __main__ - INFO - File "/app/DBolt/main.py", line 8, in <module>
2024-08-19 13:56:49,387 - __main__ - INFO - import discord
2024-08-19 13:56:49,387 - __main__ - INFO - ModuleNotFoundError: No module named 'discord'
2024-08-19 13:57:08,636 - __main__ - INFO - Bot started successfully.
2024-08-19 13:57:09,056 - __main__ - INFO - Installing module discord.py...
2024-08-19 13:57:09,189 - __main__ - INFO - Install output for discord.py: 
2024-08-19 13:57:09,189 - __main__ - INFO - Error installing discord.py: 
2024-08-19 13:57:09,512 - __main__ - INFO - Traceback (most recent call last):
2024-08-19 13:57:09,512 - __main__ - INFO - File "/app/DBolt/main.py", line 8, in <module>
2024-08-19 13:57:09,513 - __main__ - INFO - import discord
2024-08-19 13:57:09,513 - __main__ - INFO - ModuleNotFoundError: No module named 'discord'
2024-08-19 13:57:38,009 - __main__ - INFO - Bot started successfully.
2024-08-19 13:57:38,431 - __main__ - INFO - Installing module discord.py...
2024-08-19 13:57:38,554 - __main__ - INFO - Install output for discord.py: 
2024-08-19 13:57:38,554 - __main__ - INFO - Error installing discord.py: 
2024-08-19 13:57:38,854 - __main__ - INFO - Traceback (most recent call last):
2024-08-19 13:57:38,854 - __main__ - INFO - File "/app/DBolt/main.py", line 8, in <module>
2024-08-19 13:57:38,855 - __main__ - INFO - import discord
2024-08-19 13:57:38,855 - __main__ - INFO - ModuleNotFoundError: No module named 'discord'
2024-08-19 14:00:38,276 - __main__ - INFO - Bot started successfully.
2024-08-19 14:00:38,660 - __main__ - INFO - Error in DBolt: BotProcess.install_modules() got an unexpected keyword argument 'modules'
2024-08-19 14:00:38,661 - __main__ - INFO - Bot Process stopped, which was running before 0s
2024-08-19 14:00:56,459 - __main__ - INFO - Bot started successfully.
2024-08-19 14:00:56,796 - __main__ - INFO - Installing modules...
2024-08-19 14:00:56,917 - __main__ - INFO - Install output: 
2024-08-19 14:00:56,917 - __main__ - INFO - Error installing modules: 
2024-08-19 14:00:57,269 - __main__ - INFO - Traceback (most recent call last):
2024-08-19 14:00:57,270 - __main__ - INFO - File "/app/DBolt/main.py", line 8, in <module>
2024-08-19 14:00:57,271 - __main__ - INFO - import discord
2024-08-19 14:00:57,271 - __main__ - INFO - ModuleNotFoundError: No module named 'discord'
2024-08-19 14:01:46,359 - __main__ - INFO - Bot started successfully.
2024-08-19 14:01:46,743 - __main__ - INFO - Installing modules...
2024-08-19 14:01:46,873 - __main__ - INFO - Install output: 
2024-08-19 14:01:46,874 - __main__ - INFO - Error installing modules: 
2024-08-19 14:01:47,186 - __main__ - INFO - Traceback (most recent call last):
2024-08-19 14:01:47,186 - __main__ - INFO - File "/app/DBolt/main.py", line 8, in <module>
2024-08-19 14:01:47,187 - __main__ - INFO - import discord
2024-08-19 14:01:47,187 - __main__ - INFO - ModuleNotFoundError: No module named 'discord'
2024-08-19 14:02:42,263 - __main__ - INFO - Bot started successfully.
2024-08-19 14:02:42,609 - __main__ - INFO - Installing modules...
2024-08-19 14:02:42,721 - __main__ - INFO - Install output: 
2024-08-19 14:02:42,721 - __main__ - INFO - Error installing modules: 
2024-08-19 14:02:43,058 - __main__ - INFO - Traceback (most recent call last):
2024-08-19 14:02:43,058 - __main__ - INFO - File "/app/DBolt/main.py", line 8, in <module>
2024-08-19 14:02:43,059 - __main__ - INFO - import discord
2024-08-19 14:02:43,060 - __main__ - INFO - ModuleNotFoundError: No module named 'discord'
2024-08-19 14:03:47,345 - __main__ - INFO - Bot started successfully.
2024-08-19 14:03:47,713 - __main__ - INFO - Installing modules...
2024-08-19 14:03:47,816 - __main__ - INFO - Install output: 
2024-08-19 14:03:47,817 - __main__ - INFO - Error installing modules: 
2024-08-19 14:03:48,179 - __main__ - INFO - Traceback (most recent call last):
2024-08-19 14:03:48,179 - __main__ - INFO - File "/app/DBolt/main.py", line 8, in <module>
2024-08-19 14:03:48,179 - __main__ - INFO - import discord
2024-08-19 14:03:48,179 - __main__ - INFO - ModuleNotFoundError: No module named 'discord'
2024-08-19 14:04:16,889 - __main__ - INFO - Bot started successfully.
2024-08-19 14:04:17,260 - __main__ - INFO - Installing modules...
2024-08-19 14:04:17,366 - __main__ - INFO - Install output: 
2024-08-19 14:04:17,367 - __main__ - INFO - Error installing modules: 
2024-08-19 14:04:17,367 - __main__ - INFO - Checking installed packages...
2024-08-19 14:04:17,674 - __main__ - INFO - Error in DBolt: 409 Client Error for http+docker://localnpipe/v1.46/containers/f3ff42c813dd412daf9e40caa2e262a8708e630b9e8e6c17f779d2ac0c359dff/exec: Conflict ("container f3ff42c813dd412daf9e40caa2e262a8708e630b9e8e6c17f779d2ac0c359dff is not running")
2024-08-19 14:04:17,675 - __main__ - INFO - Bot Process stopped, which was running before 0s
2024-08-19 14:06:10,230 - __main__ - INFO - Bot started successfully.
2024-08-19 14:06:10,605 - __main__ - INFO - Installing modules...
2024-08-19 14:06:10,705 - __main__ - INFO - Install output: 
2024-08-19 14:06:10,705 - __main__ - INFO - Error installing modules: 
2024-08-19 14:06:10,706 - __main__ - INFO - Checking installed packages...
2024-08-19 14:06:11,046 - __main__ - INFO - Error in DBolt: 409 Client Error for http+docker://localnpipe/v1.46/containers/aa9177150ad9fcd7b18ca0d4cfd7a70990cb2e9d024de96384b28442818a9e0a/exec: Conflict ("container aa9177150ad9fcd7b18ca0d4cfd7a70990cb2e9d024de96384b28442818a9e0a is not running")
2024-08-19 14:06:11,047 - __main__ - INFO - Bot Process stopped, which was running before 0s
2024-08-19 14:10:02,232 - __main__ - INFO - Bot started successfully.
2024-08-19 14:10:02,612 - __main__ - INFO - Installing modules...
2024-08-19 14:10:04,719 - __main__ - INFO - Install output: ERROR: Could not open requirements file: [Errno 2] No such file or directory: '/appDBoltrequirements.txt'

[notice] A new release of pip is available: 24.0 -> 24.2
[notice] To update, run: pip install --upgrade pip

2024-08-19 14:10:04,720 - __main__ - INFO - Error installing modules: ERROR: Could not open requirements file: [Errno 2] No such file or directory: '/appDBoltrequirements.txt'

[notice] A new release of pip is available: 24.0 -> 24.2
[notice] To update, run: pip install --upgrade pip

2024-08-19 14:10:04,721 - __main__ - INFO - Checking installed packages...
2024-08-19 14:10:05,108 - __main__ - INFO - Installed packages: Package    Version
---------- -------
pip        24.0
setuptools 65.5.1
wheel      0.44.0

[notice] A new release of pip is available: 24.0 -> 24.2
[notice] To update, run: pip install --upgrade pip

2024-08-19 14:10:53,839 - __main__ - INFO - Bot started successfully.
2024-08-19 14:10:54,208 - __main__ - INFO - Installing modules...
2024-08-19 14:10:55,962 - __main__ - INFO - Install output: ERROR: Could not open requirements file: [Errno 2] No such file or directory: '/requirements.txt'

[notice] A new release of pip is available: 24.0 -> 24.2
[notice] To update, run: pip install --upgrade pip

2024-08-19 14:10:55,963 - __main__ - INFO - Error installing modules: ERROR: Could not open requirements file: [Errno 2] No such file or directory: '/requirements.txt'

[notice] A new release of pip is available: 24.0 -> 24.2
[notice] To update, run: pip install --upgrade pip

2024-08-19 14:10:55,964 - __main__ - INFO - Checking installed packages...
2024-08-19 14:10:56,375 - __main__ - INFO - Installed packages: Package    Version
---------- -------
pip        24.0
setuptools 65.5.1
wheel      0.44.0

[notice] A new release of pip is available: 24.0 -> 24.2
[notice] To update, run: pip install --upgrade pip

2024-08-19 14:11:39,470 - __main__ - INFO - Bot started successfully.
2024-08-19 14:11:40,183 - __main__ - INFO - Installing modules...
2024-08-19 14:11:42,292 - __main__ - INFO - Install output: ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'appDBoltrequirements.txt'

[notice] A new release of pip is available: 24.0 -> 24.2
[notice] To update, run: pip install --upgrade pip

2024-08-19 14:11:42,293 - __main__ - INFO - Error installing modules: ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'appDBoltrequirements.txt'

[notice] A new release of pip is available: 24.0 -> 24.2
[notice] To update, run: pip install --upgrade pip

2024-08-19 14:11:42,294 - __main__ - INFO - Checking installed packages...
2024-08-19 14:11:42,677 - __main__ - INFO - Installed packages: Package    Version
---------- -------
pip        24.0
setuptools 65.5.1
wheel      0.44.0

[notice] A new release of pip is available: 24.0 -> 24.2
[notice] To update, run: pip install --upgrade pip

2024-08-19 14:13:12,217 - __main__ - INFO - Bot started successfully.
2024-08-19 14:13:12,924 - __main__ - INFO - Upgrading pip...
2024-08-19 14:13:16,976 - __main__ - INFO - Installing modules...
2024-08-19 14:14:15,575 - __main__ - INFO - Bot started successfully.
2024-08-19 14:14:16,233 - __main__ - INFO - Upgrading pip...
2024-08-19 14:14:20,131 - __main__ - INFO - Installing modules...
2024-08-19 14:14:20,463 - __main__ - INFO - Install output: 
Usage:   
  pip install [options] <requirement specifier> [package-index-options] ...
  pip install [options] -r <requirements file> [package-index-options] ...
  pip install [options] [-e] <vcs project url> ...
  pip install [options] [-e] <local project path> ...
  pip install [options] <archive url/path> ...

--root-user-action option requires 1 argument

2024-08-19 14:14:20,464 - __main__ - INFO - Error installing modules: 
Usage:   
  pip install [options] <requirement specifier> [package-index-options] ...
  pip install [options] -r <requirements file> [package-index-options] ...
  pip install [options] [-e] <vcs project url> ...
  pip install [options] [-e] <local project path> ...
  pip install [options] <archive url/path> ...

--root-user-action option requires 1 argument

2024-08-19 14:14:20,465 - __main__ - INFO - Checking installed packages...
2024-08-19 14:14:20,714 - __main__ - INFO - Installed packages: Package    Version
---------- -------
pip        24.2
setuptools 65.5.1
wheel      0.44.0

2024-08-19 14:15:49,807 - __main__ - INFO - Bot started successfully.
2024-08-19 14:15:50,462 - __main__ - INFO - Upgrading pip...
2024-08-19 14:15:54,727 - __main__ - INFO - Installing modules...
2024-08-19 14:18:32,818 - __main__ - INFO - Bot started successfully.
2024-08-19 14:18:33,491 - __main__ - INFO - Upgrading pip...
2024-08-19 14:18:37,674 - __main__ - INFO - Installing modules...
2024-08-19 14:18:41,893 - __main__ - INFO - Error in DBolt: 'str' object has no attribute 'decode'
2024-08-19 14:18:41,893 - __main__ - INFO - Bot Process stopped, which was running before 0s
2024-08-19 14:19:31,340 - __main__ - INFO - Bot started successfully.
2024-08-19 14:19:32,034 - __main__ - INFO - Upgrading pip...
2024-08-19 14:19:35,993 - __main__ - INFO - Installing modules...
2024-08-19 14:21:09,821 - __main__ - INFO - Bot started successfully.
2024-08-19 14:21:10,201 - __main__ - INFO - Upgrading pip...
2024-08-19 14:21:14,166 - __main__ - INFO - Installing modules...
2024-08-19 14:22:27,527 - __main__ - INFO - Bot started successfully.
2024-08-19 14:22:27,929 - __main__ - INFO - Upgrading pip...
2024-08-19 14:22:31,764 - __main__ - INFO - Installing modules...
2024-08-19 14:22:36,201 - __main__ - INFO - Modules installed successfully!
2024-08-19 14:23:22,618 - __main__ - INFO - Bot started successfully.
2024-08-19 14:23:22,997 - __main__ - INFO - Upgrading pip...
2024-08-19 14:23:26,742 - __main__ - INFO - Installing modules...
2024-08-19 14:23:31,084 - __main__ - INFO - Modules installed successfully!
2024-08-19 14:24:34,121 - __main__ - INFO - Upgrading pip...
2024-08-19 14:24:37,598 - __main__ - INFO - Installing modules...
2024-08-19 14:24:41,823 - __main__ - INFO - Modules installed successfully!
2024-08-19 14:24:41,824 - __main__ - INFO - Bot started successfuly!
2024-08-19 14:25:25,944 - __main__ - INFO - Upgrading pip...
2024-08-19 14:25:29,467 - __main__ - INFO - Installing modules...
2024-08-19 14:25:33,682 - __main__ - INFO - Modules installed successfully!
2024-08-19 14:25:33,682 - __main__ - INFO - Bot started successfuly!
2024-08-19 15:05:16,001 - __main__ - INFO - Upgrading pip...
2024-08-19 15:05:16,240 - __main__ - INFO - Installing modules...
2024-08-19 15:05:16,598 - __main__ - INFO - Error in DBolt: 409 Client Error for http+docker://localnpipe/v1.46/containers/37dbac339843f79deb77b68f52cf30113653bb7f669a82ff7de6d723821a33f3/exec: Conflict ("container 37dbac339843f79deb77b68f52cf30113653bb7f669a82ff7de6d723821a33f3 is not running")
2024-08-19 15:05:16,598 - __main__ - INFO - Bot Process stopped, which was running before 0s
2024-08-19 15:08:42,482 - __main__ - INFO - Upgrading pip...
2024-08-19 15:08:46,496 - __main__ - INFO - Installing modules...
2024-08-19 15:08:50,372 - __main__ - INFO - Modules installed successfully!
2024-08-19 15:08:50,372 - __main__ - INFO - Starting bot script with command: python /app/DBolt/main.py
2024-08-19 15:08:50,383 - __main__ - INFO - Error in DBolt: 'CancellableStream' object is not subscriptable
2024-08-19 15:08:50,384 - __main__ - INFO - Bot Process stopped, which was running before 0s
2024-08-19 15:11:00,394 - __main__ - INFO - Upgrading pip...
2024-08-19 15:11:04,230 - __main__ - INFO - Installing modules...
2024-08-19 15:11:08,655 - __main__ - INFO - Modules installed successfully!
2024-08-19 15:11:08,655 - __main__ - INFO - Starting bot script with command: python /app/DBolt/main.py
2024-08-19 15:11:08,667 - __main__ - INFO - Error in DBolt: 'CancellableStream' object is not subscriptable
2024-08-19 15:11:08,668 - __main__ - INFO - Bot Process stopped, which was running before 0s
2024-08-19 15:11:53,463 - __main__ - INFO - Upgrading pip...
2024-08-19 15:11:57,042 - __main__ - INFO - Installing modules...
2024-08-19 15:12:01,434 - __main__ - INFO - Modules installed successfully!
2024-08-19 15:12:01,434 - __main__ - INFO - Starting bot script with command: python /app/DBolt/main.py
2024-08-19 15:12:01,448 - __main__ - INFO - Error in DBolt: 'CancellableStream' object is not subscriptable
2024-08-19 15:12:01,449 - __main__ - INFO - Bot Process stopped, which was running before 0s
2024-08-19 15:13:09,856 - __main__ - INFO - Upgrading pip...
2024-08-19 15:13:13,533 - __main__ - INFO - Installing modules...
2024-08-19 15:13:18,222 - __main__ - INFO - Modules installed successfully!
2024-08-19 15:13:18,222 - __main__ - INFO - Starting bot script with command: python /app/DBolt/main.py
2024-08-19 15:13:18,234 - __main__ - INFO - Error in DBolt: 'CancellableStream' object is not subscriptable
2024-08-19 15:13:18,235 - __main__ - INFO - Bot Process stopped, which was running before 0s
2024-08-19 15:14:15,925 - __main__ - INFO - Upgrading pip...
2024-08-19 15:14:19,532 - __main__ - INFO - Installing modules...
2024-08-19 15:14:23,866 - __main__ - INFO - Modules installed successfully!
2024-08-19 15:14:23,866 - __main__ - INFO - Starting bot script with command: python /app/DBolt/main.py
2024-08-19 15:14:24,206 - __main__ - INFO - Error in DBolt: 'tuple' object has no attribute 'strip'
2024-08-19 15:14:24,206 - __main__ - INFO - Bot Process stopped, which was running before 0s
2024-08-19 15:14:49,560 - __main__ - INFO - Upgrading pip...
2024-08-19 15:14:52,985 - __main__ - INFO - Installing modules...
2024-08-19 15:14:57,267 - __main__ - INFO - Modules installed successfully!
2024-08-19 15:14:57,268 - __main__ - INFO - Starting bot script with command: python /app/DBolt/main.py
2024-08-19 15:14:57,615 - __main__ - INFO - Error in DBolt: 'NoneType' object has no attribute 'strip'
2024-08-19 15:14:57,615 - __main__ - INFO - Bot Process stopped, which was running before 0s
2024-08-19 15:15:18,233 - __main__ - INFO - Upgrading pip...
2024-08-19 15:15:21,771 - __main__ - INFO - Installing modules...
2024-08-19 15:15:27,295 - __main__ - INFO - Modules installed successfully!
2024-08-19 15:15:27,295 - __main__ - INFO - Starting bot script with command: python /app/DBolt/main.py
2024-08-19 15:15:27,632 - __main__ - INFO - Error in DBolt: 'NoneType' object has no attribute 'strip'
2024-08-19 15:15:27,632 - __main__ - INFO - Bot Process stopped, which was running before 0s
2024-08-19 15:16:53,876 - __main__ - INFO - Upgrading pip...
2024-08-19 15:16:57,543 - __main__ - INFO - Installing modules...
2024-08-19 15:17:01,861 - __main__ - INFO - Modules installed successfully!
2024-08-19 15:17:01,862 - __main__ - INFO - Starting bot script with command: python /app/DBolt/main.py
2024-08-19 15:17:02,212 - __main__ - INFO - Output: [30;1m2024-08-19 14:17:02[0m [34;1mINFO    [0m [35mdiscord.client[0m logging in using static token
2024-08-19 15:17:03,185 - __main__ - INFO - Output: [30;1m2024-08-19 14:17:03[0m [34;1mINFO    [0m [35mdiscord.gateway[0m Shard ID None has connected to Gateway (Session ID: be670022e89daea22039e7220b0263c3).
2024-08-19 15:18:07,025 - DBolt - INFO - Upgrading pip...
2024-08-19 15:18:10,470 - DBolt - INFO - Installing modules...
2024-08-19 15:18:16,778 - DBolt - INFO - Modules installed successfully!
2024-08-19 15:18:16,778 - DBolt - INFO - Starting bot script with command: python /app/DBolt/main.py
2024-08-19 15:18:17,156 - DBolt - INFO - Output: [30;1m2024-08-19 14:18:17[0m [34;1mINFO    [0m [35mdiscord.client[0m logging in using static token
2024-08-19 15:18:18,208 - DBolt - INFO - Output: [30;1m2024-08-19 14:18:18[0m [34;1mINFO    [0m [35mdiscord.gateway[0m Shard ID None has connected to Gateway (Session ID: ce3f96a9ff2eefc4572a4e12c8ffb500).
2024-08-19 15:21:44,188 - DBolt - INFO - Upgrading pip...
2024-08-19 15:21:47,587 - DBolt - INFO - Installing modules...
2024-08-19 15:21:51,433 - DBolt - INFO - Modules installed successfully!
2024-08-19 15:21:51,433 - DBolt - INFO - Starting bot script with command: python /app/DBolt/main.py
2024-08-19 15:21:51,787 - DBolt - INFO - Output: [30;1m2024-08-19 14:21:51[0m [34;1mINFO    [0m [35mdiscord.client[0m logging in using static token
2024-08-19 15:21:52,883 - DBolt - INFO - Output: [30;1m2024-08-19 14:21:52[0m [34;1mINFO    [0m [35mdiscord.gateway[0m Shard ID None has connected to Gateway (Session ID: 9177a49c5c248f81bf5add7c91abbbaa).
2024-08-19 15:22:03,040 - DBolt - INFO - Output: /app/DBolt/main.py:26: RuntimeWarning: coroutine 'Messageable.send' was never awaited
  channel.send(content)
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
2024-08-19 15:22:47,735 - DBolt - INFO - Upgrading pip...
2024-08-19 15:22:51,090 - DBolt - INFO - Installing modules...
2024-08-19 15:22:54,853 - DBolt - INFO - Modules installed successfully!
2024-08-19 15:22:54,853 - DBolt - INFO - Starting bot script with command: python /app/DBolt/main.py
2024-08-19 15:22:55,203 - DBolt - INFO - Output: [30;1m2024-08-19 14:22:55[0m [34;1mINFO    [0m [35mdiscord.client[0m logging in using static token
2024-08-19 15:22:56,285 - DBolt - INFO - Output: [30;1m2024-08-19 14:22:56[0m [34;1mINFO    [0m [35mdiscord.gateway[0m Shard ID None has connected to Gateway (Session ID: ccdff5d36db9c5559e5ddb33689de5aa).
2024-08-19 15:27:48,917 - DBolt - INFO - Upgrading pip...
2024-08-19 15:27:56,982 - DBolt - INFO - Installing modules...
2024-08-19 15:28:01,587 - DBolt - INFO - Modules installed successfully!
2024-08-19 15:28:01,587 - DBolt - INFO - Starting bot script with command: python /app/DBolt/main.py
2024-08-19 15:28:01,990 - DBolt - INFO - Output: [30;1m2024-08-19 14:28:01[0m [34;1mINFO    [0m [35mdiscord.client[0m logging in using static token
2024-08-19 15:28:03,153 - DBolt - INFO - Output: [30;1m2024-08-19 14:28:03[0m [34;1mINFO    [0m [35mdiscord.gateway[0m Shard ID None has connected to Gateway (Session ID: f68a4bfe497c1e4e3ed915446b5c8a7e).
2024-08-19 15:28:19,116 - DBolt - INFO - Output: [30;1m2024-08-19 14:28:19[0m [31mERROR   [0m [35mdiscord.client[0m Ignoring exception in on_message
[31mTraceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/discord/client.py", line 449, in _run_event
    await coro(*args, **kwargs)
  File "/app/DBolt/main.py", line 25, in on_message
    content, user, channel = message.conten, message.author, message.channel
                             ^^^^^^^^^^^^^^
AttributeError: 'Message' object has no attribute 'conten'[0m
2024-08-19 15:29:32,579 - DBolt - INFO - Upgrading pip...
2024-08-19 15:29:36,616 - DBolt - INFO - Installing modules...
2024-08-19 15:29:40,563 - DBolt - INFO - Modules installed successfully!
2024-08-19 15:29:40,563 - DBolt - INFO - Starting bot script with command: python /app/DBolt/main.py
2024-08-19 15:29:40,928 - DBolt - INFO - Output: [30;1m2024-08-19 14:29:40[0m [34;1mINFO    [0m [35mdiscord.client[0m logging in using static token
2024-08-19 15:29:42,172 - DBolt - INFO - Output: [30;1m2024-08-19 14:29:42[0m [34;1mINFO    [0m [35mdiscord.gateway[0m Shard ID None has connected to Gateway (Session ID: a3694962c28082627500b34a33969847).
2024-08-19 15:30:42,672 - DBolt - WARNING - Upgrading pip...
2024-08-19 15:30:46,383 - DBolt - WARNING - Installing modules...
2024-08-19 15:30:50,326 - DBolt - INFO - Modules installed successfully!
2024-08-19 15:30:50,327 - DBolt - INFO - Starting bot script with command: python /app/DBolt/main.py
2024-08-19 15:30:50,672 - DBolt - INFO - Output: [30;1m2024-08-19 14:30:50[0m [34;1mINFO    [0m [35mdiscord.client[0m logging in using static token
2024-08-19 15:30:51,968 - DBolt - INFO - Output: [30;1m2024-08-19 14:30:51[0m [34;1mINFO    [0m [35mdiscord.gateway[0m Shard ID None has connected to Gateway (Session ID: 970e2dd02dcb2f572030cdd36980b40e).
2024-08-19 15:31:22,319 - DBolt - WARNING - Upgrading pip...
2024-08-19 15:31:26,068 - DBolt - WARNING - Installing modules...
2024-08-19 15:31:31,275 - DBolt - INFO - Modules installed successfully!
2024-08-19 15:31:31,275 - DBolt - INFO - Starting bot script with command: python /app/DBolt/main.py
2024-08-19 15:31:31,621 - DBolt - INFO - Output: Traceback (most recent call last):
  File "/app/DBolt/main.py", line 9, in <module>
2024-08-19 15:31:31,624 - DBolt - INFO - Output: import jiscord
ModuleNotFoundError: No module named 'jiscord'
2024-08-19 15:33:25,015 - DBolt - WARNING - Upgrading pip...
2024-08-19 15:33:28,845 - DBolt - WARNING - Installing modules...
2024-08-19 15:33:33,279 - DBolt - INFO - Modules installed successfully!
2024-08-19 15:33:33,279 - DBolt - INFO - Starting bot script with command: python /app/DBolt/main.py
2024-08-19 15:33:33,621 - DBolt - INFO - Output: Traceback (most recent call last):
  File "/app/DBolt/main.py", line 9, in <module>
2024-08-19 15:33:33,624 - DBolt - INFO - Output: import jiscord
ModuleNotFoundError: No module named 'jiscord'
2024-08-19 15:34:08,001 - DBolt - WARNING - Upgrading pip...
2024-08-19 15:34:12,080 - DBolt - WARNING - Installing modules...
2024-08-19 15:34:16,363 - DBolt - INFO - Modules installed successfully!
2024-08-19 15:34:16,363 - DBolt - INFO - Starting bot script with command: python /app/DBolt/main.py
2024-08-19 15:34:16,702 - DBolt - INFO - Output: [30;1m2024-08-19 14:34:16[0m [34;1mINFO    [0m [35mdiscord.client[0m logging in using static token
2024-08-19 15:34:17,718 - DBolt - INFO - Output: [30;1m2024-08-19 14:34:17[0m [34;1mINFO    [0m [35mdiscord.gateway[0m Shard ID None has connected to Gateway (Session ID: 9d35ce959b62945338d64f4a3fda442d).
2024-08-19 15:36:17,016 - DBolt - INFO - Output: [30;1m2024-08-19 14:36:17[0m [31mERROR   [0m [35mdiscord.client[0m Ignoring exception in on_message
[31mTraceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/discord/client.py", line 449, in _run_event
    await coro(*args, **kwargs)
  File "/app/DBolt/main.py", line 25, in on_message
    content, user, channel = message.conten, message.author, message.channel
                             ^^^^^^^^^^^^^^
AttributeError: 'Message' object has no attribute 'conten'[0m
2024-08-24 17:17:07,690 - DBolt - WARNING - Upgrading pip...
2024-08-24 17:17:11,542 - DBolt - WARNING - Installing modules...
2024-08-24 17:17:15,418 - DBolt - INFO - Modules installed successfully!
2024-08-24 17:17:15,418 - DBolt - INFO - Starting bot script with command: python /app/DBolt/main.py
2024-08-24 17:17:15,837 - DBolt - INFO - Output: [30;1m2024-08-24 16:17:15[0m [34;1mINFO    [0m [35mdiscord.client[0m logging in using static token
2024-08-24 17:17:16,103 - DBolt - INFO - Output: Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/discord/http.py", line 816, in static_login
2024-08-24 17:17:16,104 - DBolt - INFO - Output: data = await self.request(Route('GET', '/users/@me'))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/discord/http.py", line 758, in request
2024-08-24 17:17:16,104 - DBolt - INFO - Output: raise HTTPException(response, data)
discord.errors.HTTPException: 401 Unauthorized (error code: 0): 401: Unauthorized

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
2024-08-24 17:17:16,105 - DBolt - INFO - Output: File "/app/DBolt/main.py", line 21, in <module>
2024-08-24 17:17:16,107 - DBolt - INFO - Output: client.run("MTI2MDk4MTQ1MjQ2NDQ1NTczNA.Gu4POZ.dzFo41pfzSf1dVjastP-IV3giFX1N1sOdNJbjE")
  File "/usr/local/lib/python3.11/site-packages/discord/client.py", line 869, in run
2024-08-24 17:17:16,108 - DBolt - INFO - Output: asyncio.run(runner())
  File "/usr/local/lib/python3.11/asyncio/runners.py", line 190, in run
2024-08-24 17:17:16,109 - DBolt - INFO - Output: return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/runners.py", line 118, in run
2024-08-24 17:17:16,109 - DBolt - INFO - Output: return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 654, in run_until_complete
2024-08-24 17:17:16,110 - DBolt - INFO - Output: return future.result()
           ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/discord/client.py", line 858, in runner
2024-08-24 17:17:16,111 - DBolt - INFO - Output: await self.start(token, reconnect=reconnect)
  File "/usr/local/lib/python3.11/site-packages/discord/client.py", line 786, in start
2024-08-24 17:17:16,111 - DBolt - INFO - Output: await self.login(token)
  File "/usr/local/lib/python3.11/site-packages/discord/client.py", line 620, in login
2024-08-24 17:17:16,112 - DBolt - INFO - Output: data = await self.http.static_login(token)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/discord/http.py", line 820, in static_login
2024-08-24 17:17:16,113 - DBolt - INFO - Output: raise LoginFailure('Improper token has been passed.') from exc
discord.errors.LoginFailure: Improper token has been passed.
2024-08-24 17:18:24,781 - DBolt - WARNING - Upgrading pip...
2024-08-24 17:18:29,268 - DBolt - WARNING - Installing modules...
2024-08-24 17:18:33,618 - DBolt - INFO - Modules installed successfully!
2024-08-24 17:18:33,618 - DBolt - INFO - Starting bot script with command: python /app/DBolt/main.py
2024-08-24 17:18:33,958 - DBolt - INFO - Output: [30;1m2024-08-24 16:18:33[0m [34;1mINFO    [0m [35mdiscord.client[0m logging in using static token
2024-08-24 17:18:34,234 - DBolt - INFO - Output: Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/discord/http.py", line 816, in static_login
2024-08-24 17:18:34,235 - DBolt - INFO - Output: data = await self.request(Route('GET', '/users/@me'))
2024-08-24 17:18:34,235 - DBolt - INFO - Output: ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/discord/http.py", line 758, in request
2024-08-24 17:18:34,236 - DBolt - INFO - Output: raise HTTPException(response, data)
discord.errors.HTTPException: 401 Unauthorized (error code: 0): 401: Unauthorized

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/app/DBolt/main.py", line 21, in <module>
2024-08-24 17:18:34,238 - DBolt - INFO - Output: client.run("MTI2MDk4MTQ1MjQ2NDQ1NTczNA.Gu4POZ.dzFo41pfzSf1dVjastP-IV3giFX1N1sOdNJbjE")
  File "/usr/local/lib/python3.11/site-packages/discord/client.py", line 869, in run
2024-08-24 17:18:34,238 - DBolt - INFO - Output: asyncio.run(runner())
  File "/usr/local/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
2024-08-24 17:18:34,240 - DBolt - INFO - Output: ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/runners.py", line 118, in run
2024-08-24 17:18:34,241 - DBolt - INFO - Output: return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 654, in run_until_complete
2024-08-24 17:18:34,241 - DBolt - INFO - Output: return future.result()
           ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/discord/client.py", line 858, in runner
2024-08-24 17:18:34,242 - DBolt - INFO - Output: await self.start(token, reconnect=reconnect)
  File "/usr/local/lib/python3.11/site-packages/discord/client.py", line 786, in start
2024-08-24 17:18:34,242 - DBolt - INFO - Output: await self.login(token)
  File "/usr/local/lib/python3.11/site-packages/discord/client.py", line 620, in login
2024-08-24 17:18:34,243 - DBolt - INFO - Output: data = await self.http.static_login(token)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/discord/http.py", line 820, in static_login
2024-08-24 17:18:34,244 - DBolt - INFO - Output: raise LoginFailure('Improper token has been passed.') from exc
discord.errors.LoginFailure: Improper token has been passed.
2024-08-24 17:20:09,886 - DBolt - WARNING - Upgrading pip...
2024-08-24 17:20:13,971 - DBolt - WARNING - Installing modules...
2024-08-24 17:20:18,128 - DBolt - INFO - Modules installed successfully!
2024-08-24 17:20:18,128 - DBolt - INFO - Starting bot script with command: python /app/DBolt/main.py
2024-08-24 17:20:18,474 - DBolt - INFO - Output: [30;1m2024-08-24 16:20:18[0m [34;1mINFO    [0m [35mdiscord.client[0m logging in using static token
2024-08-24 17:20:18,694 - DBolt - INFO - Output: Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/discord/http.py", line 816, in static_login
2024-08-24 17:20:18,695 - DBolt - INFO - Output: data = await self.request(Route('GET', '/users/@me'))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/discord/http.py", line 758, in request
2024-08-24 17:20:18,696 - DBolt - INFO - Output: raise HTTPException(response, data)
discord.errors.HTTPException: 401 Unauthorized (error code: 0): 401: Unauthorized

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/app/DBolt/main.py", line 21, in <module>
2024-08-24 17:20:18,697 - DBolt - INFO - Output: client.run("MTI2MDk4MTQ1MjQ2NDQ1NTczNA.Gu4POZ.dzFo41pfzSf1dVjastP-IV3giFX1N1sOdNJbjE")
  File "/usr/local/lib/python3.11/site-packages/discord/client.py", line 869, in run
2024-08-24 17:20:18,698 - DBolt - INFO - Output: asyncio.run(runner())
  File "/usr/local/lib/python3.11/asyncio/runners.py", line 190, in run
2024-08-24 17:20:18,698 - DBolt - INFO - Output: return runner.run(main)
2024-08-24 17:20:18,699 - DBolt - INFO - Output: ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/runners.py", line 118, in run
2024-08-24 17:20:18,700 - DBolt - INFO - Output: return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 654, in run_until_complete
2024-08-24 17:20:18,701 - DBolt - INFO - Output: return future.result()
           ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/discord/client.py", line 858, in runner
2024-08-24 17:20:18,701 - DBolt - INFO - Output: await self.start(token, reconnect=reconnect)
  File "/usr/local/lib/python3.11/site-packages/discord/client.py", line 786, in start
2024-08-24 17:20:18,702 - DBolt - INFO - Output: await self.login(token)
  File "/usr/local/lib/python3.11/site-packages/discord/client.py", line 620, in login
2024-08-24 17:20:18,702 - DBolt - INFO - Output: data = await self.http.static_login(token)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/discord/http.py", line 820, in static_login
2024-08-24 17:20:18,703 - DBolt - INFO - Output: raise LoginFailure('Improper token has been passed.') from exc
discord.errors.LoginFailure: Improper token has been passed.
2024-08-24 17:20:48,132 - DBolt - WARNING - Upgrading pip...
2024-08-24 17:20:52,238 - DBolt - WARNING - Installing modules...
2024-08-24 17:20:57,141 - DBolt - INFO - Modules installed successfully!
2024-08-24 17:20:57,141 - DBolt - INFO - Starting bot script with command: python /app/DBolt/main.py
2024-08-24 17:20:57,563 - DBolt - INFO - Output: [30;1m2024-08-24 16:20:57[0m [34;1mINFO    [0m [35mdiscord.client[0m logging in using static token
2024-08-24 17:20:58,801 - DBolt - INFO - Output: [30;1m2024-08-24 16:20:58[0m [34;1mINFO    [0m [35mdiscord.gateway[0m Shard ID None has connected to Gateway (Session ID: e22d0ae1e409639a1ad0066cc9708495).
2024-08-24 17:21:14,662 - DBolt - INFO - Output: [30;1m2024-08-24 16:21:14[0m [31mERROR   [0m [35mdiscord.client[0m Ignoring exception in on_message
[31mTraceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/discord/client.py", line 449, in _run_event
    await coro(*args, **kwargs)
  File "/app/DBolt/main.py", line 18, in on_message
    content, user, channel = message.conten, message.author, message.channel
                             ^^^^^^^^^^^^^^
AttributeError: 'Message' object has no attribute 'conten'[0m
2024-08-24 17:21:52,981 - DBolt - WARNING - Upgrading pip...
2024-08-24 17:21:57,219 - DBolt - WARNING - Installing modules...
2024-08-24 17:22:01,793 - DBolt - INFO - Modules installed successfully!
2024-08-24 17:22:01,793 - DBolt - INFO - Starting bot script with command: python /app/DBolt/main.py
2024-08-24 17:22:02,202 - DBolt - INFO - Output: [30;1m2024-08-24 16:22:02[0m [34;1mINFO    [0m [35mdiscord.client[0m logging in using static token
2024-08-24 17:22:03,312 - DBolt - INFO - Output: [30;1m2024-08-24 16:22:03[0m [34;1mINFO    [0m [35mdiscord.gateway[0m Shard ID None has connected to Gateway (Session ID: f17b2711a0df19e82d4e19e6d3b27f2a).
